# Generated by Django 4.2.1 on 2023-07-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, default="media/default.jpg", upload_to="post_pics"
            ),
        ),
    ]
