# -*- coding: utf-8 -*-
"""QuesAns.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pK4X0H87CT2cnyHZVLdkcz2Iwp727ul4
"""


# from transformers import DistilBertTokenizer, TFDistilBertForQuestionAnswering
# import tensorflow as tf

# tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-cased-distilled-squad")
# model = TFDistilBertForQuestionAnswering.from_pretrained("distilbert-base-cased-distilled-squad")

question = "whats your email address?"
# text = "{'name': Albert Osei, email: albert@gmai.com, 'education': 'University of London', 'location': 'Ghana', 'website-name': 'https://devwithcode.com', 'siblings': '5 siblings', 'marital status':'single', 'age': '36 years old'}"

text = "Albert Osei is my name and my email address is albert@gmai.com, I'm a computer scinece student at University of London.I'm a Ghanaian and was born in a town called Asamankese. I have 5 siblings and I'm not married.You can also look for me on my personal website 'https://devwithcode.com'"

# inputs = tokenizer(question, text, return_tensors="tf")
# outputs = model(**inputs)

# answer_start_index = int(tf.math.argmax(outputs.start_logits, axis=-1)[0])
# answer_end_index = int(tf.math.argmax(outputs.end_logits, axis=-1)[0])

# predict_answer_tokens = inputs.input_ids[0, answer_start_index : answer_end_index + 1]
# tokenizer.decode(predict_answer_tokens)


def chatbot_answers(question):
    tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-cased-distilled-squad")
    model = TFDistilBertForQuestionAnswering.from_pretrained("distilbert-base-cased-distilled-squad") 

    inputs = tokenizer(question, text, return_tensors="tf")
    outputs = model(**inputs)

    answer_start_index = int(tf.math.argmax(outputs.start_logits, axis=-1)[0])
    answer_end_index = int(tf.math.argmax(outputs.end_logits, axis=-1)[0])

    predict_answer_tokens = inputs.input_ids[0, answer_start_index : answer_end_index + 1]
    return tokenizer.decode(predict_answer_tokens)


print(chatbot_answers(question))
